# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFBc8Iqld4I4q6X0hKa3tk0dCQ6RCDYP
"""

print("Hello, world")
print("")